const data = {
  1: {
    title: "Chakraalu",
    telugu_title: "చక్రాలు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357628/chekaralu_nzt2mo.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  2: {
    title: "Chekkalu",
    telugu_title: "చెక్కలు",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729428568/chekkalu_jiovga-removebg-preview_jwlkzh.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  3: {
    title: "Ribbon Pakodi",
    telugu_title: "రిబ్బన్ పకోడీ",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729428138/ribbon_pakodi_n858lk-removebg-preview_ga4cur.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  4: {
    title: "Sunnundalu",
    telugu_title: "సున్నుండలు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357636/sunnundalu_nr5oxk.png",
    quantity: {
      1: "5 pieces",
      2: "10 pieces",
      3: "20 pieces",
      more: "more ...",
    },
    price: {
      1: "100 ₹",
      2: "200 ₹",
      3: "370 ₹",
    },
  },
  5: {
    title: "Bellam Nuvvula Laddu",
    telugu_title: "బెల్లం నువ్వుల లడ్డు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357633/Nuvulaladdu_berjog.png",
    quantity: {
      1: "5 pieces",
      2: "10 pieces",
      3: "20 pieces",
      more: "more ...",
    },
    price: {
      1: "75 ₹",
      2: "150 ₹",
      3: "200 ₹",
    },
  },
  6: {
    title: "Boondhi",
    telugu_title: "బూందీ",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729428500/boondhi_tukpup-removebg-preview_ucfjxz.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  7: {
    title: "Bellam Gavvalu",
    telugu_title: "గవ్వలు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357627/Bellam_Gavvalu_eyneba.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  9: {
    title: "Kaaram Gavvalu",
    telugu_title: "కారం గవ్వలు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357629/Karam_Gavvalu_ezhm2i.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  10: {
    title: "Theepi Kommulu",
    telugu_title: "తీపి కొమ్ములు",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357637/tepikumulu_zblzyt.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  11: {
    title: "Boondhi Laddo",
    title: "Boondhi Laddo",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357633/laddu_si55qz.png",
    quantity: {
      1: "5 pieces",
      2: "10 pieces",
      3: "20 pieces",
      more: "more ...",
    },
    price: {
      1: "100 ₹",
      2: "200 ₹",
      3: "370 ₹",
    },
  },
  12: {
    title: "Karappusa",
    telugu_title: "కారప్పుస",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357632/karappusa_z8omjz.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  13: {
    title: "Panasa Thonalu",
    telugu_title: "పనస తోనాలు",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729428871/PANASA_THONALU-removebg-preview_1_osmero.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  14: {
    title: "Avakai Pickle",
    telugu_title: "ఆవకాయ",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357628/Avakaya_muaa7t.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  15: {
    title: "Tomato Pickle",
    telugu_title: "టమోటా పచ్చడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357638/tomatopickle_i6vhvp.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  16: {
    title: "Usirikaya Pickle",
    telugu_title: "ఉసిరికాయ పచ్చడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357230/usirikaya_pickle_nb2zdp.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  17: {
    title: "Gongura Pickle",
    telugu_title: "గోంగూర పచ్చడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729357629/gongurapickle_ayh₹o.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  18: {
    title: "Cauliflower Pickle",
    telugu_title: "కాలీఫ్లవర్ ఊరగాయ",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729532224/Cauliflower-Pickle-removebg-preview_nrsmwz.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },
  18: {
    title: "pandu mirchi pickle",
    telugu_title: "పండు మిర్చి పచ్చడి",
    image:
      "https://res.cloudinary.com/dnmf69odi/image/upload/v1729532824/pandumirchi1-e1720236092225-removebg-preview_fprlod.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "200 ₹",
      quater: "100 ₹",
      1: "400 ₹",
      2: "800 ₹",
      3: "1200 ₹",
      4: "1600 ₹",
    },
  },

  20: {
    title: "Kobbari Kaaram Podi",
    telugu_title: "కొబ్బరి కారం పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532719/kobbari_karam_podi-removebg-preview_xocv8u.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  21: {
    title: "Kaarappodi",
    telugu_title: "కారప్పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532672/karappodi-removebg-preview_arxnm0.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  22: {
    title: "Pappula Podi",
    telugu_title: "పప్పుల పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532574/mix_pappula_podi-removebg-preview_rmfabf.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  23: {
    title: "Karivepaku Podi",
    telugu_title: "కరివేపాకు పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532532/curry_leaf_podi-removebg-preview_k8avqe.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  24: {
    title: "Munagaaku Podi",
    telugu_title: "మునగాకు పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532205/munagaaku_podi-removebg-preview_fugycd.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  25: {
    title: "Avisa Ginjala Podi",
    telugu_title: "అవిసె గింజల పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532159/avisa_ginjala_podi-removebg-preview_udq2zy.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  26: {
    title: "Senaga Podi",
    telugu_title: "సెనగ పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532105/senaga_podi-removebg-preview_v1u0te.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
  27: {
    title: "Rasam Powder",
    telugu_title: "రసం పొడి",
    image:
      "https://res.cloudinary.com/dhjygngv2/image/upload/v1729532024/Rasam-Powder-removebg-preview_b6se3f.png",
    quantity: {
      half: "1/2 kg",
      quater: "1/4 kg",
      1: "1 kg",
      2: "2 kg",
      3: "3 kg",
      more: "more ...",
    },
    price: {
      half: "",
      quater: "",
      1: "",
      2: "",
      3: "",
      4: "",
    },
  },
};

export default data;
